language: go

go:
- tip

sudo: false
dist: trusty


before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- go get github.com/kisielk/errcheck

script:
- go test -v -race -parallel=1 -timeout=5m $(go list github.com/optiopay/kafka/... | grep -v integration)
- go test -bench '.*' -benchmem -run none $(go list github.com/optiopay/kafka/... | grep -v integration)
- go vet github.com/optiopay/kafka/...
- errcheck github.com/optiopay/kafka/...

env:
- WITH_INTEGRATION=true GOMAXPROCS=4
