language: go
go:
- 1.4
- tip


before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- go get golang.org/x/tools/cmd/vet
- go get github.com/kisielk/errcheck

script:
- go test -v -race ./...
- go vet ./...
- errcheck ./...

sudo: false
