language: go
go:
- 1.4.2
- tip


before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- go get golang.org/x/tools/cmd/vet
- go get github.com/kisielk/errcheck

script:
- go test -v -race -timeout=60s github.com/optiopay/kafka/...
- go vet github.com/optiopay/kafka/...
- errcheck github.com/optiopay/kafka/...

sudo: false
