language: go

go:
- tip

sudo: false
dist: trusty


before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- go get github.com/kisielk/errcheck

script:
- go vet github.com/optiopay/kafka/...
- errcheck github.com/optiopay/kafka/...
- go test -v -race -timeout=5m $(go list github.com/optiopay/kafka/... | grep -v integration)

env:
- WITH_INTEGRATION=false GOMAXPROCS=4
